### ISSUE TITLE
Filter by location

### ISSUE THREAD

**Issue by mourner** [mapbox/team-directory#6]
Currently you can filter only by name. It would be awesome to be able to filter by location too — e.g. enter "Germany" to see quickly who's from Germany. Also would be cool to use fuzzy filtering so e.g. "Vldimir" would match "Vladimir" — there are nice JS libs for this.

**Comment by tristen** [comment]
Fuzzy filtering is in and passing `city` to `options.filterKeys` on implementation (See https://github.com/mapbox/team-directory/blob/master/GETTING_STARTED.md#initializing) should enable filtering by location.
